# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-gSkA4zcoP2wABxOLEKDKUPEnFXAB4T
"""

#  (1)

def store_1():

    print("Welcome to our Ecommerce Store!")

    print("\nCategories:")
    print("1. Electronics")
    print("2. Clothing")
    print("3. Books")

    while True:
        try:
            category_choice = int(input("Choose a category (1-3): "))
            if 1 <= category_choice <= 3:
                break
            else:
                print("Invalid category choice. Please enter a number between 1 and 3.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    if category_choice == 1:
        print("\nElectronics:")
        print("1. Smartphone - $500")
        print("2. Laptop - $1000")
        print("3. Headphones - $150")
        print("4. Smartwatch - $250")
        print("5. Camera - $700")
        prices = [500, 1000, 150, 250, 700]
    elif category_choice == 2:
        print("\nClothing:")
        print("1. T-Shirt - $20")
        print("2. Jeans - $40")
        print("3. Jacket - $80")
        print("4. Shoes - $60")
        print("5. Dress - $50")
        prices = [20, 40, 80, 60, 50]
    else:
        print("\nBooks:")
        print("1. Novel - $15")
        print("2. Textbook - $30")
        print("3. Comic Book - $10")
        print("4. Biography - $25")
        print("5. Cookbook - $20")
        prices = [15, 30, 10, 25, 20]

    while True:
        try:
            item_choice = int(input("Choose an item (1-5): "))
            if 1 <= item_choice <= 5:
                break
            else:
                print("Invalid item choice. Please enter a number between 1 and 5.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    item_price = prices[item_choice - 1]
    print(f"\nItem price: ${item_price}")

    checkout_choice = input("\nCheckout? (yes/no): ").lower()
    if checkout_choice == "yes":
        print(f"\nThank you for your purchase! Your total is ${item_price}.")
    else:
        print("\nYour item has been removed from the cart.")

store_1()
                            # (2)

# def store_2():
#     print("Welcome to our Ecommerce Store!")

#     print("\nCategories:")
#     print("1. Electronics")
#     print("2. Clothing")
#     print("3. Books")
#     category_choice = int(input("Choose a category (1-3): "))

#     if category_choice == 1:
#         print("\nElectronics:")
#         print("1. Smartphone - $500")
#         print("2. Laptop - $1000")
#         print("3. Headphones - $150")
#         print("4. Smartwatch - $250")
#         print("5. Camera - $700")
#     elif category_choice == 2:
#         print("\nClothing:")
#         print("1. T-Shirt - $20")
#         print("2. Jeans - $40")
#         print("3. Jacket - $80")
#         print("4. Shoes - $60")
#         print("5. Dress - $50")
#     elif category_choice == 3:
#         print("\nBooks:")
#         print("1. Novel - $15")
#         print("2. Textbook - $30")
#         print("3. Comic Book - $10")
#         print("4. Biography - $25")
#         print("5. Cookbook - $20")
#     else:
#         print("Invalid category choice. Please try again.")
#         return

#     item_choice = int(input("Choose an item (1-5): "))

#     if 1 <= item_choice <= 5:
#         if category_choice == 1:
#             prices = [500, 1000, 150, 250, 700]
#         elif category_choice == 2:
#             prices = [20, 40, 80, 60, 50]
#         else:
#             prices = [15, 30, 10, 25, 20]

#         item_price = prices[item_choice - 1]
#         print(f"\nItem price: ${item_price}")
#     else:
#         print("Invalid item choice. Please try again.")
#         return

#     checkout_choice = input("\nCheckout? (yes/no): ")
#     if checkout_choice.lower() == "yes":
#         print(f"\nThank you for your purchase! Your total is ${item_price}.")
#     else:
#         print("\nYour item has been removed from the cart.")
# store_2()



                            # (3)


# player_name = input("Enter the player's name: ")
# matches_played = int(input("Enter the number of matches played: "))
# runs_scored = int(input("Enter the total runs scored: "))
# wickets_taken = int(input("Enter the total wickets taken (0 if not a bowler): "))

# batting_average = runs_scored / matches_played if matches_played > 0 else 0

# if matches_played >= 50 and batting_average >= 50:
#     print(f"{player_name} is a world-class batsman!")
# elif matches_played >= 30 and batting_average >= 40:
#     print(f"{player_name} is a promising batsman.")
# elif wickets_taken >= 50:
#     print(f"{player_name} is a successful bowler!")
# elif wickets_taken >= 20:
#     print(f"{player_name} is a developing bowler.")
# else:
#     print(f"{player_name} is a valuable team player.")

                                # (4)

# import random


# card1 = random.randint(1, 13)
# card2 = random.randint(1, 13)

# print("Card 1:", card1)
# print("Card 2:", card2)

# if card1 > card2:
#     print("Player 1 wins!")
# elif card2 > card1:
#     print("Player 2 wins!")
# else:
#     print("It's a tie!")





